### ISSUE TITLE
Error but maybe still worked?

### ISSUE THREAD

**Issue by ecwheele** [byee4/annotator#2]
```
[ecwheele@tscc-1-37 annotator]$ python annotate.py --input /projects/ps-yeolab3/clip_not_encode/ecwheele/20170614_SRSF2_eirini_all_clip/clipper_intjob_test/EW42_SRSF2_C1-8_diff_IP.merged.r2.peaks.for.kmers.bed --output /projects/ps-yeolab3/clip_not_encode/ecwheele/20170614_SRSF2_eirini_all_clip/clipper_intjob_test/EW42_SRSF2_C1-8_diff_IP.merged.r2.peaks.for.kmers.bed.annotated.bed --gtfdb /projects/ps-yeolab/genomes/hg19/gencode_v19/gencode.v19.annotation.gtf.db


Initializing/creating defs:  14%|#####8                                   | 1/7 [00:00<00:01,  5.46it/s]featuretypes = ['cds', 'selenocysteine', 'utr', 'exon', 'gene', 'start_codon', 'stop_codon', 'transcript']
Adding all CDS boundaries: 100%|##########################################| 7/7 [08:38<00:00, 76.37s/it]Traceback (most recent call last):                                                                      
  File "annotate.py", line 163, in <module>
    main()
  File "annotate.py", line 159, in main
    transcript_priority, gene_priority, species, append_chr, fuzzy
  File "build/bdist.linux-x86_64/egg/annotator/Annotator.py", line 661, in annotate
    interval, unstranded, transcript_priority, gene_priority,
ValueError: need more than 2 values to unpack
```

But the output looks like this:

```[ecwheele@tscc-1-37 annotator]$ less -S /projects/ps-yeolab3/clip_not_encode/ecwheele/20170614_SRSF2_eirini_all_clip/clipper_intjob_test/EW42_SRSF2_C1-8_diff_IP.merged.r2.peaks.for.kmers.bed.annotated.bed
chr1    17460   17568   3.5     6.13602943803   -       noncoding_exon  WASH7P  ENSG00000227232.4       
chr1    18350   18366   3.5     -3.47868845335  -       noncoding_exon  WASH7P  ENSG00000227232.4       
chr1    24737   24749   3.5     -3.45734563282  -       noncoding_exon  WASH7P  ENSG00000227232.4       
chr1    135156  135268  3.5     1.27031936123   -       3UTR    AL627309.1      ENSG00000237683.5       
chr1    135160  135268  3.5     -0.387692423984 -       3UTR    AL627309.1      ENSG00000237683.5       
chr1    137793  137852  3.5     0.13758028368   -       3UTR    AL627309.1      ENSG00000237683.5       
chr1    137794  137844  3.5     -2.14554667036  -       3UTR    AL627309.1      ENSG00000237683.5       
chr1    137963  137997  3.5     -3.83516567863  -       3UTR    AL627309.1      ENSG00000237683.5       
chr1    139037  139088  3.5     -0.768221275007 -       CDS     AL627309.1      ENSG00000237683.5
```

**Comment by byee4** [comment]
What's the command you used?

**Comment by ecwheele** [comment]
It is at the top of that gist. Yeah it annotated some, but not all peaks. 

```
python annotate.py --input /projects/ps-yeolab3/clip_not_encode/ecwheele/20170614_SRSF2_eirini_all_clip/clipper_intjob_test/EW42_SRSF2_C1-8_diff_IP.merged.r2.peaks.for.kmers.bed --output /projects/ps-yeolab3/clip_not_encode/ecwheele/20170614_SRSF2_eirini_all_clip/clipper_intjob_test/EW42_SRSF2_C1-8_diff_IP.merged.r2.peaks.for.kmers.bed.annotated.bed --gtfdb /projects/ps-yeolab/genomes/hg19/gencode_v19/gencode.v19.annotation.gtf.db```

**Comment by byee4** [comment]
small bug when trying to annotate intergenic regions

try the latest commit (command is now annotate-bed)

**Comment by ecwheele** [comment]
I removed the old directory entirely. A fresh git clone followed by build and install still doesn't give me the annotate-bed command. which annotate-bed doesn't find anything.

**Comment by byee4** [comment]
sorry try again

**Comment by byee4** [comment]
Fixed bug that failed upon finding intergenic regions. This should be fixed.
